server:
  port: 8090
  servlet:
    session:
      cookie:
        name: KSESSION
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://${AUTH_SERVER}/oauth/authorize
      access-token-uri: http://${AUTH_SERVER}/oauth/token
    resource:
      token-info-uri: http://${AUTH_SERVER}/oauth/check_token
      